// indexpage
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li>
          <Link href="/note">
            <a>note</a>
          </Link>
        </li>
        <li>
          <Link href="/analyze">
            <a>analysis</a>
          </Link>
        </li>
        <li>
          <Link href="/journal">
            <a>journal</a>
          </Link>
        </li>
        <li>
          <Link href="/reagent">
            <a>reagent</a>
          </Link>
        </li>
        <li>
          <Link href="/blog">
            <a>blog</a>
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;

// // function HomePage() {
//   function Blog({ posts }) {
//     console.log(posts);
//     // 記事のレンダー
//     return (
//       <ul>
//           <li>{posts.title}</li>
//       </ul>
//     );
//   }
  
//   // この関数はビルド時に呼ばれる
//   export async function getStaticProps() {
//     // 投稿記事を取得する外部APIエンドポイントをコール
//     const res = await fetch('http://app:5000/app/hello');
//     const posts = await res.json();
//     console.log(posts)
  
//     // { props: posts }を返すことで、ビルド時にBlogコンポーネントが
//     // `posts`をpropとして受け取れる
//     return {
//       props: {
//         posts
//       }
//     };
//   }
  
//   export default Home;
  