import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li>
          <Link href="/note">
            <a>実験記録</a>
          </Link>
        </li>
        <li>
          <Link href="/analysis">
            <a>解析用のページ</a>
          </Link>
        </li>
        <li>
          <Link href="/blog/">
            <a>開発記録</a>
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;